create table oyc_club_events (
	event_id VARCHAR(50),
	date DATE,
	description TEXT
);
insert into oyc_club_events (event_id, date, description) values ('1110', '2007-11-19', 'primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec');
insert into oyc_club_events (event_id, date, description) values ('1060', '2007-09-30', 'lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam');
insert into oyc_club_events (event_id, date, description) values ('1980', '2008-07-27', 'curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi');
insert into oyc_club_events (event_id, date, description) values ('1513', '2007-09-26', 'sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus');
insert into oyc_club_events (event_id, date, description) values ('1760', '2008-05-30', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam');
insert into oyc_club_events (event_id, date, description) values ('1489', '2007-11-29', 'turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc');
insert into oyc_club_events (event_id, date, description) values ('1492', '2008-07-03', 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo');
insert into oyc_club_events (event_id, date, description) values ('1731', '2008-03-13', 'augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst');
insert into oyc_club_events (event_id, date, description) values ('1031', '2008-01-27', 'ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent');
insert into oyc_club_events (event_id, date, description) values ('1641', '2008-06-30', 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa');
insert into oyc_club_events (event_id, date, description) values ('1614', '2008-01-07', 'nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis');
insert into oyc_club_events (event_id, date, description) values ('1235', '2008-03-29', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula');
insert into oyc_club_events (event_id, date, description) values ('1442', '2007-10-05', 'a nibh in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices');
insert into oyc_club_events (event_id, date, description) values ('1541', '2008-07-19', 'potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus');
insert into oyc_club_events (event_id, date, description) values ('1577', '2008-07-24', 'turpis adipiscing lorem vitae mattis nibh ligula nec sem duis');
insert into oyc_club_events (event_id, date, description) values ('1723', '2008-01-13', 'elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam');
insert into oyc_club_events (event_id, date, description) values ('1571', '2008-06-28', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into oyc_club_events (event_id, date, description) values ('1669', '2008-04-08', 'molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst');
insert into oyc_club_events (event_id, date, description) values ('1829', '2007-12-21', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis');
insert into oyc_club_events (event_id, date, description) values ('1521', '2007-09-23', 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus');
insert into oyc_club_events (event_id, date, description) values ('1178', '2008-04-21', 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris');
insert into oyc_club_events (event_id, date, description) values ('1249', '2008-05-19', 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus morbi');
insert into oyc_club_events (event_id, date, description) values ('1833', '2008-04-04', 'tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc');
insert into oyc_club_events (event_id, date, description) values ('1513', '2008-02-02', 'nulla integer pede justo lacinia eget tincidunt eget tempus vel pede');
insert into oyc_club_events (event_id, date, description) values ('1995', '2007-11-21', 'dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non');
insert into oyc_club_events (event_id, date, description) values ('1636', '2008-04-01', 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum');
insert into oyc_club_events (event_id, date, description) values ('1076', '2008-04-08', 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate');
insert into oyc_club_events (event_id, date, description) values ('1920', '2008-03-04', 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur');
insert into oyc_club_events (event_id, date, description) values ('1297', '2008-04-02', 'dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis');
insert into oyc_club_events (event_id, date, description) values ('1413', '2008-08-25', 'erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer');
insert into oyc_club_events (event_id, date, description) values ('1731', '2008-01-01', 'ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non');
insert into oyc_club_events (event_id, date, description) values ('1682', '2008-03-04', 'id massa id nisl venenatis lacinia aenean sit amet justo morbi ut');
insert into oyc_club_events (event_id, date, description) values ('1261', '2008-06-20', 'elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis');
insert into oyc_club_events (event_id, date, description) values ('1637', '2007-09-18', 'quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst maecenas ut massa');
insert into oyc_club_events (event_id, date, description) values ('1683', '2008-08-28', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat');
insert into oyc_club_events (event_id, date, description) values ('1531', '2007-10-07', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at');
insert into oyc_club_events (event_id, date, description) values ('1080', '2008-05-19', 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante');
insert into oyc_club_events (event_id, date, description) values ('1654', '2008-02-24', 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum');
insert into oyc_club_events (event_id, date, description) values ('1638', '2008-07-05', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio');
insert into oyc_club_events (event_id, date, description) values ('1056', '2008-04-30', 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque');
insert into oyc_club_events (event_id, date, description) values ('1583', '2007-10-04', 'eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor');
insert into oyc_club_events (event_id, date, description) values ('1415', '2007-09-05', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris');
insert into oyc_club_events (event_id, date, description) values ('1395', '2008-08-15', 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam');
insert into oyc_club_events (event_id, date, description) values ('1996', '2007-10-13', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat');
insert into oyc_club_events (event_id, date, description) values ('1861', '2007-11-02', 'mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam');
insert into oyc_club_events (event_id, date, description) values ('1317', '2007-12-13', 'porta volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla');
insert into oyc_club_events (event_id, date, description) values ('1950', '2008-06-15', 'adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere nonummy');
insert into oyc_club_events (event_id, date, description) values ('1365', '2008-02-12', 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim');
insert into oyc_club_events (event_id, date, description) values ('1621', '2008-04-09', 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus');
insert into oyc_club_events (event_id, date, description) values ('1856', '2007-09-20', 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a pede posuere');
insert into oyc_club_events (event_id, date, description) values ('1315', '2007-11-30', 'at nulla suspendisse potenti cras in purus eu magna vulputate luctus');
insert into oyc_club_events (event_id, date, description) values ('1391', '2007-10-13', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum');
insert into oyc_club_events (event_id, date, description) values ('1809', '2007-09-21', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie');
insert into oyc_club_events (event_id, date, description) values ('1656', '2008-06-12', 'pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper');
insert into oyc_club_events (event_id, date, description) values ('1382', '2008-03-13', 'eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus');
insert into oyc_club_events (event_id, date, description) values ('1088', '2007-09-24', 'augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere');
insert into oyc_club_events (event_id, date, description) values ('1426', '2008-04-04', 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla');
insert into oyc_club_events (event_id, date, description) values ('1158', '2007-11-29', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis');
insert into oyc_club_events (event_id, date, description) values ('1741', '2008-06-26', 'aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio');
insert into oyc_club_events (event_id, date, description) values ('1908', '2007-10-28', 'sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi');
insert into oyc_club_events (event_id, date, description) values ('1544', '2008-04-17', 'blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi');
insert into oyc_club_events (event_id, date, description) values ('1377', '2008-07-09', 'tristique est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante');
insert into oyc_club_events (event_id, date, description) values ('1162', '2008-05-29', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet');
insert into oyc_club_events (event_id, date, description) values ('1829', '2008-06-11', 'sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus');
insert into oyc_club_events (event_id, date, description) values ('1256', '2007-09-10', 'dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into oyc_club_events (event_id, date, description) values ('1520', '2007-09-24', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim');
insert into oyc_club_events (event_id, date, description) values ('1936', '2008-03-28', 'morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue');
insert into oyc_club_events (event_id, date, description) values ('1286', '2008-08-27', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
insert into oyc_club_events (event_id, date, description) values ('1534', '2007-12-05', 'lobortis ligula sit amet eleifend pede libero quis orci nullam molestie');
insert into oyc_club_events (event_id, date, description) values ('1796', '2007-11-29', 'primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet');
insert into oyc_club_events (event_id, date, description) values ('1601', '2007-09-05', 'cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget');
insert into oyc_club_events (event_id, date, description) values ('1177', '2008-05-30', 'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices');
insert into oyc_club_events (event_id, date, description) values ('1383', '2007-11-12', 'cursus urna ut tellus nulla ut erat id mauris vulputate');
insert into oyc_club_events (event_id, date, description) values ('1512', '2007-11-12', 'id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie');
insert into oyc_club_events (event_id, date, description) values ('1334', '2008-02-05', 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci');
insert into oyc_club_events (event_id, date, description) values ('1789', '2007-11-03', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam');
insert into oyc_club_events (event_id, date, description) values ('1944', '2008-02-15', 'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque');
insert into oyc_club_events (event_id, date, description) values ('1590', '2007-11-29', 'sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet');
insert into oyc_club_events (event_id, date, description) values ('1452', '2007-11-29', 'ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar');
insert into oyc_club_events (event_id, date, description) values ('1238', '2008-06-13', 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into oyc_club_events (event_id, date, description) values ('1022', '2008-04-21', 'quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in');
insert into oyc_club_events (event_id, date, description) values ('1615', '2008-04-27', 'eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc');
insert into oyc_club_events (event_id, date, description) values ('1378', '2008-02-15', 'amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien');
insert into oyc_club_events (event_id, date, description) values ('1508', '2007-09-20', 'mauris sit amet eros suspendisse accumsan tortor quis turpis sed');
insert into oyc_club_events (event_id, date, description) values ('1208', '2008-02-02', 'sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula');
insert into oyc_club_events (event_id, date, description) values ('1839', '2008-01-14', 'lectus in est risus auctor sed tristique in tempus sit amet');
insert into oyc_club_events (event_id, date, description) values ('1675', '2008-09-27', 'A going way party for Tim!');
